spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/classifier?currentSchema=spring
    driver-class-name: org.postgresql.Driver
server:
  port: 80