CREATE DATABASE users
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
CREATE SCHEMA IF NOT EXISTS spring
    AUTHORIZATION postgres;
	

CREATE TABLE IF NOT EXISTS spring.users
(
    uuid uuid NOT NULL,
    dt_create timestamp(3) without time zone,
    dt_update timestamp(3) without time zone,
    mail character varying(50) NOT NULL COLLATE pg_catalog."default",
    nick character varying(30) NOT NULL COLLATE pg_catalog."default",
    role character varying(10) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    password character varying(8) NOT NULL COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (uuid),
    CONSTRAINT unique_mail_key UNIQUE (mail),
    CONSTRAINT unique_nick_key UNIQUE (mail)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS spring.users
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS spring.authorities
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
role_name text COLLATE pg_catalog."default",
CONSTRAINT authorities_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS spring.authorities
OWNER to postgres;